"build": {
  "appId": "com.simplesystemssoftware.RuttersPlus",
  "productName": "RuttersPlus",
  "electronVersion": "28.2.3",
  "publish": null,
  "files": [
    "**/*",
    "assets/**/*",
    "media/**/*"
  ],
  "extraResources": [
    { "from": "media/", "to": "media/" },
    { "from": "Mac/", "to": "Mac/" },
    { "from": "Windows/", "to": "Windows/" },
    { "from": "assets/", "to": "assets/" },
    { "from": "node_modules/node-wifi", "to": "node_modules/node-wifi" }
  ],
  "directories": {
    "buildResources": "assets"
  },
  "win": {
    "icon": "Windows/RuttersLogo.ico",
    "target": "nsis"
  },
  "mac": {
    "icon": "Mac/RuttersLogo.icns",
    "target": "dmg",
    "identity": null
  },
  "linux": {
    "icon": "assets/linux-icon.png",
    "category": "Utility",
    "target": [ "AppImage", "deb" ]
  }
}
        with:
          name: mac-build
          path: dist/
